import re
import time
from pathlib import Path
from html import unescape

import requests
from bs4 import BeautifulSoup


URL = "https://bhpwebout.posta.ba/KalkulatorCijena_WEB_app/Bos/Default.aspx"

AVAILABLE_FILE = Path("available_countries.txt")
SUSPENDED_FILE = Path("suspended_countries.txt")

WEIGHT = "10"

SUSPENDED_MESSAGE = (
    "Prijem pošiljaka se trenutno ne vrši za odabranu državu"
)

HEADERS = {
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/139.0 Safari/537.36"
    ),
}


def get_hidden_fields(html):
    soup = BeautifulSoup(html, "html.parser")

    data = {}

    for element in soup.select("input[type='hidden']"):
        name = element.get("name")
        if name:
            data[name] = element.get("value", "")

    return data


def parse_countries(html):
    soup = BeautifulSoup(html, "html.parser")

    select = soup.find("select", id="ddlMeDoOdrediste")

    if not select:
        return []

    result = []

    for option in select.find_all("option"):
        value = option.get("value")
        name = option.get_text(strip=True)

        if value and name:
            result.append((value, name))

    return result


def post_async(session, html, event_target, extra=None):
    """
    ASP.NET UpdatePanel postback.
    """

    data = get_hidden_fields(html)

    data["__EVENTTARGET"] = event_target
    data["__EVENTARGUMENT"] = ""
    data["__ASYNCPOST"] = "true"

    if extra:
        data.update(extra)

    headers = {
        **HEADERS,
        "X-Requested-With": "XMLHttpRequest",
        "X-MicrosoftAjax": "Delta=true",
        "Referer": URL,
    }

    response = session.post(
        URL,
        data=data,
        headers=headers,
        timeout=90,
    )

    response.raise_for_status()

    return response.text


def post_normal(session, html, extra):
    """
    Normal ASP.NET form POST.
    """

    data = get_hidden_fields(html)
    data.update(extra)

    headers = {
        **HEADERS,
        "Referer": URL,
    }

    response = session.post(
        URL,
        data=data,
        headers=headers,
        timeout=90,
    )

    response.raise_for_status()

    return response.text


def find_text(html, text):
    return text in unescape(html)


def activate_international(session, html):
    """
    Your browser showed that after clicking the international
    tab the page reports:

        activeTabIndex: 1

    The tab control itself is ASPxTabControl1.
    """

    print("Activating Međunarodni promet...")

    # The actual ASPx tab control is client-side and its tab
    # postback is normally generated by DevExpress JavaScript.
    #
    # First check whether we are already there.
    if "ddlMeDoOdrediste" in html:
        return html

    # Try the known tab control callback.
    data = get_hidden_fields(html)

    data["__EVENTTARGET"] = "ASPxTabControl1"
    data["__EVENTARGUMENT"] = "1"
    data["__ASYNCPOST"] = "true"

    response = session.post(
        URL,
        data=data,
        headers={
            **HEADERS,
            "X-Requested-With": "XMLHttpRequest",
            "X-MicrosoftAjax": "Delta=true",
            "Referer": URL,
        },
        timeout=90,
    )

    response.raise_for_status()

    html = response.text

    if "ddlMeDoOdrediste" not in html:
        raise RuntimeError(
            "Could not activate Međunarodni promet. "
            "The server did not return ddlMeDoOdrediste."
        )

    return html


def activate_dopisnica(session, html):
    """
    ImageButton8 is the Dopisnica control according to the
    HTML you supplied.
    """

    if "ddlMeDoOdrediste" not in html:
        raise RuntimeError(
            "Country selector is missing before Dopisnica."
        )

    print("Dopisnica selected.")

    # If Dopisnica is already active, don't click it again.
    if "Dopisnica_Aktivna.png" in html:
        return html

    html = post_normal(
        session,
        html,
        {
            "ImageButton8.x": "1",
            "ImageButton8.y": "1",
        },
    )

    if "Dopisnica_Aktivna.png" not in html:
        print(
            "Warning: Dopisnica_Aktivna.png was not found "
            "after clicking ImageButton8."
        )

    return html


def activate_airmail(session, html):
    """
    Enable:

        chbMeDoAvionski

    """

    soup = BeautifulSoup(html, "html.parser")

    checkbox = soup.find(
        "input",
        id="chbMeDoAvionski"
    )

    if not checkbox:
        raise RuntimeError(
            "Could not find chbMeDoAvionski."
        )

    if checkbox.has_attr("checked"):
        print("Avionski prijenos already enabled.")
        return html

    print("Enabling Avionski prijenos...")

    html = post_async(
        session,
        html,
        "chbMeDoAvionski",
        {
            "chbMeDoAvionski": "on",
        },
    )

    soup = BeautifulSoup(html, "html.parser")

    checkbox = soup.find(
        "input",
        id="chbMeDoAvionski"
    )

    if not checkbox or not checkbox.has_attr("checked"):
        raise RuntimeError(
            "Avionski prijenos could not be enabled."
        )

    return html


def select_country(session, html, code):
    """
    Reproduce:

        ddlMeDoOdrediste
        onchange -> __doPostBack(...)
    """

    return post_async(
        session,
        html,
        "ddlMeDoOdrediste",
        {
            "ddlMeDoOdrediste": code,
        },
    )


def calculate(session, html, code):
    """
    Calculate 10 g airmail postcard price/status.
    """

    return post_normal(
        session,
        html,
        {
            "ddlMeDoOdrediste": code,
            "chbMeDoAvionski": "on",
            "tbxMeDoAvioTezina": WEIGHT,
            "btnMeDoIzracunaj": "Izračunaj",
        },
    )


def is_suspended(html):
    return SUSPENDED_MESSAGE in unescape(html)


def is_available(html):
    text = BeautifulSoup(
        unescape(html),
        "html.parser"
    ).get_text(" ", strip=True)

    if "Ukupna cijena" in text:
        return True

    if re.search(
        r"\b\d+(?:[,.]\d+)?\s*KM\b",
        text
    ):
        return True

    return False


def main():

    session = requests.Session()
    session.headers.update(HEADERS)

    print("Opening calculator...")

    response = session.get(
        URL,
        timeout=90,
    )

    response.raise_for_status()

    html = response.text

    print(
        f"Initial page received: "
        f"{len(html):,} bytes"
    )

    # ---------------------------------------------------------
    # 1. Međunarodni promet
    # ---------------------------------------------------------

    html = activate_international(
        session,
        html,
    )

    # ---------------------------------------------------------
    # 2. Dopisnica
    # ---------------------------------------------------------

    html = activate_dopisnica(
        session,
        html,
    )

    # ---------------------------------------------------------
    # 3. Avionski prijenos
    # ---------------------------------------------------------

    html = activate_airmail(
        session,
        html,
    )

    # ---------------------------------------------------------
    # 4. Read List 1 source
    # ---------------------------------------------------------

    countries = parse_countries(html)

    if not countries:
        raise RuntimeError(
            "No countries found in ddlMeDoOdrediste."
        )

    print(
        f"Found {len(countries)} destination entries."
    )

    available = []
    suspended = []

    # ---------------------------------------------------------
    # 5. Test every destination at 10 g
    # ---------------------------------------------------------

    for index, (code, name) in enumerate(
        countries,
        start=1,
    ):

        print(
            f"[{index}/{len(countries)}] "
            f"{name} ({code})",
            flush=True,
        )

        try:

            # Select destination.
            html = select_country(
                session,
                html,
                code,
            )

            # Calculate.
            html = calculate(
                session,
                html,
                code,
            )

            if is_suspended(html):

                print(
                    "    -> SUSPENDED",
                    flush=True,
                )

                suspended.append(name)

            elif is_available(html):

                print(
                    "    -> AVAILABLE",
                    flush=True,
                )

                available.append(name)

            else:

                print(
                    "    -> UNKNOWN",
                    flush=True,
                )

        except Exception as exc:

            print(
                f"    -> ERROR: {exc}",
                flush=True,
            )

        time.sleep(0.5)

    # ---------------------------------------------------------
    # 6. Write raw lists
    # ---------------------------------------------------------

    AVAILABLE_FILE.write_text(
        "\n".join(available) + "\n",
        encoding="utf-8",
    )

    SUSPENDED_FILE.write_text(
        "\n".join(suspended) + "\n",
        encoding="utf-8",
    )

    print()
    print("Finished.")
    print()
    print(
        f"Available countries written to: "
        f"{AVAILABLE_FILE}"
    )
    print(
        f"Suspended countries written to: "
        f"{SUSPENDED_FILE}"
    )


if __name__ == "__main__":
    main()
